"""initial schema

Revision ID: 564c201f3137
Revises: d54d40ce6818
Create Date: 2025-12-27 14:55:33.141916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '564c201f3137'
down_revision: Union[str, Sequence[str], None] = 'd54d40ce6818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_api_products_org_id_name')
    )
    op.create_index(op.f('ix_api_products_org_id'), 'api_products', ['org_id'], unique=False)
    op.create_index('ix_api_products_org_id_is_active', 'api_products', ['org_id', 'is_active'], unique=False)
    op.create_table('app_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_app_clients_org_id_name')
    )
    op.create_index(op.f('ix_app_clients_client_id'), 'app_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_app_clients_org_id'), 'app_clients', ['org_id'], unique=False)
    op.create_index('ix_app_clients_org_id_is_active', 'app_clients', ['org_id', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_action_ts', 'audit_logs', ['actor_id', 'action', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_decision'), 'audit_logs', ['decision'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('platform_admin', 'org_admin', 'developer', name='user_role'), server_default='developer', nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index('ix_users_org_id_role', 'users', ['org_id', 'role'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['app_client_id'], ['app_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_client_id', 'name', name='uq_api_keys_app_client_id_name')
    )
    op.create_index(op.f('ix_api_keys_app_client_id'), 'api_keys', ['app_client_id'], unique=False)
    op.create_index('ix_api_keys_app_client_id_is_active', 'api_keys', ['app_client_id', 'is_active'], unique=False)
    op.create_index('ix_api_keys_app_client_id_prefix', 'api_keys', ['app_client_id', 'prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_table('api_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('base_path', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'deprecated', name='api_status'), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['api_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'base_path', 'version', name='uq_api_versions_product_id_base_path_version'),
    sa.UniqueConstraint('product_id', 'version', name='uq_api_versions_product_id_version')
    )
    op.create_index(op.f('ix_api_versions_product_id'), 'api_versions', ['product_id'], unique=False)
    op.create_index('ix_api_versions_product_id_status', 'api_versions', ['product_id', 'status'], unique=False)
    op.create_table('scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['api_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_scopes_product_id_name')
    )
    op.create_index(op.f('ix_scopes_product_id'), 'scopes', ['product_id'], unique=False)
    op.create_index('ix_scopes_product_id_name', 'scopes', ['product_id', 'name'], unique=False)
    op.create_table('endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', name='http_method'), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['api_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'method', 'path', name='uq_endpoints_version_id_method_path')
    )
    op.create_index(op.f('ix_endpoints_version_id'), 'endpoints', ['version_id'], unique=False)
    op.create_index('ix_endpoints_version_id_is_active', 'endpoints', ['version_id', 'is_active'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_client_id', sa.UUID(), nullable=False),
    sa.Column('api_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', 'revoked', name='subscription_status'), server_default='pending', nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), server_default='100', nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_version_id'], ['api_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['app_client_id'], ['app_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_client_id', 'api_version_id', name='uq_subscriptions_app_client_api_version')
    )
    op.create_index(op.f('ix_subscriptions_api_version_id'), 'subscriptions', ['api_version_id'], unique=False)
    op.create_index('ix_subscriptions_api_version_id_status', 'subscriptions', ['api_version_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_app_client_id'), 'subscriptions', ['app_client_id'], unique=False)
    op.create_index('ix_subscriptions_app_client_id_status', 'subscriptions', ['app_client_id', 'status'], unique=False)
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_table('endpoint_required_scopes',
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('endpoint_id', 'scope_id')
    )
    op.create_index('ix_endpoint_required_scopes_endpoint_id', 'endpoint_required_scopes', ['endpoint_id'], unique=False)
    op.create_index('ix_endpoint_required_scopes_scope_id', 'endpoint_required_scopes', ['scope_id'], unique=False)
    op.create_table('subscription_granted_scopes',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id', 'scope_id')
    )
    op.create_index('ix_sub_grant_scopes_scope_id', 'subscription_granted_scopes', ['scope_id'], unique=False)
    op.create_index('ix_sub_grant_scopes_subscription_id', 'subscription_granted_scopes', ['subscription_id'], unique=False)
    op.create_table('subscription_requested_scopes',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id', 'scope_id')
    )
    op.create_index('ix_sub_req_scopes_scope_id', 'subscription_requested_scopes', ['scope_id'], unique=False)
    op.create_index('ix_sub_req_scopes_subscription_id', 'subscription_requested_scopes', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sub_req_scopes_subscription_id', table_name='subscription_requested_scopes')
    op.drop_index('ix_sub_req_scopes_scope_id', table_name='subscription_requested_scopes')
    op.drop_table('subscription_requested_scopes')
    op.drop_index('ix_sub_grant_scopes_subscription_id', table_name='subscription_granted_scopes')
    op.drop_index('ix_sub_grant_scopes_scope_id', table_name='subscription_granted_scopes')
    op.drop_table('subscription_granted_scopes')
    op.drop_index('ix_endpoint_required_scopes_scope_id', table_name='endpoint_required_scopes')
    op.drop_index('ix_endpoint_required_scopes_endpoint_id', table_name='endpoint_required_scopes')
    op.drop_table('endpoint_required_scopes')
    op.drop_index('ix_subscriptions_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_app_client_id_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_app_client_id'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_api_version_id_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_api_version_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_endpoints_version_id_is_active', table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_version_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index('ix_scopes_product_id_name', table_name='scopes')
    op.drop_index(op.f('ix_scopes_product_id'), table_name='scopes')
    op.drop_table('scopes')
    op.drop_index('ix_api_versions_product_id_status', table_name='api_versions')
    op.drop_index(op.f('ix_api_versions_product_id'), table_name='api_versions')
    op.drop_table('api_versions')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_index('ix_api_keys_app_client_id_prefix', table_name='api_keys')
    op.drop_index('ix_api_keys_app_client_id_is_active', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_app_client_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_users_org_id_role', table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_decision'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_action_ts', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_app_clients_org_id_is_active', table_name='app_clients')
    op.drop_index(op.f('ix_app_clients_org_id'), table_name='app_clients')
    op.drop_index(op.f('ix_app_clients_client_id'), table_name='app_clients')
    op.drop_table('app_clients')
    op.drop_index('ix_api_products_org_id_is_active', table_name='api_products')
    op.drop_index(op.f('ix_api_products_org_id'), table_name='api_products')
    op.drop_table('api_products')
    # ### end Alembic commands ###
