"""version update

Revision ID: b157d16d4b0e
Revises: 564c201f3137
Create Date: 2025-12-27 21:31:08.615155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b157d16d4b0e'
down_revision: Union[str, Sequence[str], None] = '564c201f3137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_organizations_name')
    )
    op.create_index('ix_organizations_is_active', 'organizations', ['is_active'], unique=False)
    op.drop_index(op.f('ix_api_keys_app_client_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_app_client_id_prefix'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_expires_at'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_last_used_at'), 'api_keys', ['last_used_at'], unique=False)
    op.create_unique_constraint('uq_api_keys_key_hash', 'api_keys', ['key_hash'])
    op.create_unique_constraint('uq_api_keys_prefix', 'api_keys', ['prefix'])
    op.create_foreign_key(None, 'api_keys', 'users', ['revoked_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'api_products', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'app_clients', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column(
        'audit_logs',
        'actor_id',
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        nullable=True,
        postgresql_using='actor_id::uuid',
    )
    op.execute(
        """
        UPDATE audit_logs
        SET actor_id = NULL
        WHERE actor_id IS NOT NULL
          AND NOT EXISTS (
              SELECT 1 FROM users WHERE users.id = audit_logs.actor_id
          )
        """
    )
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'app_clients', type_='foreignkey')
    op.drop_constraint(None, 'api_products', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint('uq_api_keys_prefix', 'api_keys', type_='unique')
    op.drop_constraint('uq_api_keys_key_hash', 'api_keys', type_='unique')
    op.drop_index(op.f('ix_api_keys_last_used_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_expires_at'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_app_client_id_prefix'), 'api_keys', ['app_client_id', 'prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_app_client_id'), 'api_keys', ['app_client_id'], unique=False)
    op.drop_index('ix_organizations_is_active', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
