"""initial schema

Revision ID: d54d40ce6818
Revises: 
Create Date: 2025-12-27 14:40:48.168922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.audit_log import AuditLog
from app.models.subscription import Subscription

# revision identifiers, used by Alembic.
revision: str = 'd54d40ce6818'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
